#if !canImport(ObjectiveC)
import XCTest

extension ActionsKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ActionsKitTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ActionsKitTests.__allTests__ActionsKitTests),
    ]
}
#endif
